[tool.poetry]
name = "backend"
version = "0.1.0"
description = "Backend para o sistema Define Pilates"
authors = ["Pilates"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10"
# As dependências serão adicionadas aqui pelo comando 'poetry add'
django = "^5.2.6"
djangorestframework = "^3.16.1"
mysqlclient = "^2.2.7"
python-decouple = "^3.8"
drf-spectacular = "^0.28.0"

[tool.poetry.group.dev.dependencies]
# As dependências de desenvolvimento serão adicionadas aqui
black = "^25.9.0"
ruff = "^0.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"